routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes(['register' => false]);
// Route::get('/', 'HomeController@index')->name('home');
Route::get('/', function () {
    if(Auth::check()){
        // if(Auth::user()->isPending() || Auth::user()->isDisabled()) {
            Auth::logout();
            return redirect('/login')->with('success', 'Please Login');
        // }
        //return view('welcome');
    }
    return redirect('/home');
});
Route::group(['middleware' => ['auth']], function() {
Route::resource('users', 'UserController');
Route::resource('roles', 'RoleController');

Route::resource('permissions', 'PermissionController');
Route::resource('drivers', 'DriverController');
Route::resource('trucks', 'TrucksController');
Route::resource('drives', 'DriveController');
Route::resource('items', 'ItemsController');
Route::resource('suppliers', 'SuppliersController');
Route::resource('warehouses', 'WarehouseController');
Route::resource('purchases', 'PurchaseController');
Route::resource('services', 'ServicesController');
Route::resource('checks', 'ChecksController');
Route::resource('snduq', 'SnduqController');
Route::resource('expenses', 'ExpensesController');
Route::resource('slfa', 'SlfaController');
Route::resource('purchase_items', 'PurchaseItemController');
Route::resource('service_items', 'ServiceItemsController');
Route::resource('check_items', 'CheckItemsController');
Route::resource('accounting','AccountingController');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/expired_license', 'DriverController@expired')->name('drivers.expired');
Route::get('/serviceouts/{id}', 'ServiceOutController@services')->name('serviceOut.services');
Route::post('/update/purchase_item', 'PurchaseItemController@updatee')->name('purchase_items.updatee');
Route::post('/trip/getPrice', 'TripController@getPrice')->name('trip.getprice');
Route::post('/trip/accounting', 'AccountingController@showaccounting')->name('accountant.showaccounting');
Route::post('/trip/finishaccounting', 'AccountingController@finishaccounting')->name('accountant.finishaccounting');
Route::post('/update/service_item', 'ServiceItemsController@updatee')->name('service_items.updatee');
Route::post('/update/service_out_item', 'ServiceOutItemsController@updatee')->name('service_out_items.updatee');
Route::post('/update/check_item', 'CheckItemsController@updatee')->name('check_items.updatee');
Route::get('/trucks/expired_reg/{id}', 'TrucksController@expired_registeration')->name('trucks.expired_registeration');
Route::get('/trucks/expired_permit/{id}', 'TrucksController@expired_permit')->name('trucks.expired_permit');
Route::get('/purchases/items/{id}', 'PurchaseController@items')->name('purchases.items');
Route::get('/services/items/{id}', 'ServicesController@items')->name('services.items');
Route::get('/serviceout/items/{id}', 'ServiceOutController@items')->name('serviceOut.items');
Route::get('/cheecks/items/{id}', 'ChecksController@items')->name('checks.items');
Route::get('/items/alert/{id}', 'ItemsController@alertItems')->name('items.alert');
Route::get('/items/projectparts/{id}', 'ItemsController@projectItems')->name('items.projectparts');
Route::resource('locations','LocationsController');
Route::resource('serviceOut','ServiceOutController');
Route::resource('service_out_items','ServiceOutItemsController');
Route::resource('projects','ProjectsController');
Route::resource('projectPayment','ProjectPaymentController');
Route::get('/projectPayments/{id}', 'ProjectPaymentController@payments')->name('projectpayments.payments');
Route::resource('fines','FinesController');
Route::resource('locationCost','LocationCostController');
Route::resource('materials','MaterialController');
Route::resource('expense_type','ExpenseTypeController');
Route::resource('trips','TripController');
Route::resource('transfers','BankTransferController');
Route::resource('dollars','DollarPriceController');
Route::resource('itemModel','ItemModelController');
Route::resource('itemSize','ItemSizeController');
Route::resource('drive_payments','DrivePaymentController');
Route::resource('gass_to_trucks','GassQtyToTrucksController');
Route::resource('gass_purchase','GassQtyPurchaseController');
Route::resource('banzin_to_trucks','BanzinQtyToTrucksController');
Route::resource('banzin_purchase','BanzinQtyPurchaseController');
Route::post('monthlyReport','ReportsController@monthly')->name('reports.monthly');
Route::post('transfer/updatestatus','BankTransferController@updatee')->name('transfers.updatee');
Route::get('monthlyReport','ReportsController@monthly')->name('reports.monthly');

Route::get('clear_cache', function () {

    \Artisan::call('migrate');
    \Artisan::call('cache:clear');

    dd("Cache is cleared");

});
});

resources/views/home.blade.php
{{-- resources/views/admin/dashboard.blade.php --}}

@extends('layouts.app')

@section('title', 'Dashboard')

@if(Session::has('flash_message'))
<div class="container">
    <div class="alert alert-success"><em> {!! session('flash_message') !!}</em>
    </div>
</div>
@endif

<div class="row">
<div class="col-md-8 col-md-offset-2">
    {{-- @include ('errors.list') Including error file --}}
</div>
</div>

@section('content_header')
    <h1>پەڕەی سەرەکی</h1>
@stop

@section('content')
<style type="text/css">
.small-box{
  opacity: 0.9;
}
</style>
@php
use Carbon\Carbon;
$today_date = Carbon::today();
$today_date45 = Carbon::now()->addDays(45);
@endphp
<img src="{{ asset('img/logo.png') }}" style="width:600px;position: fixed;top:90px;opacity: 0.5;margin-left: auto; margin-right: auto;left:15%;">
<div class="row" style="margin: 20px;">

  @can('view_dollar')
	<div class="col-md-4 col-sm-12 col-xs-12 text-center responsive">
		<div class="small-box text-center bg-black color-palette "     >
            <div class="inner">
              <h3>{{ App\DollarPrice::orderby('id','desc')->first()->price}}</h3>

              <p style="font-weight: bold;color:white;">{{ __('main.dollar price') }}</p>
            </div>
            <div class="icon">
              <i class="fa fa-user-secret"></i>
            </div>
            <a href="{{ route('dollars.index') }}" class="small-box-footer">
              {{ __('main.visit') }} <i class="fa fa-arrow-circle-left"></i>
            </a>
          </div>
    </div>
    @endcan
    {{-- @can('view_driver')
  <div class="col-md-4 col-sm-12 col-xs-12 text-center">
    <div class="small-box text-center " style="    background-color: #f39c12  !important;">
            <div class="inner">
              <h3>{{ App\Driver::where('license_expire','<=',$today_date)->count() }}</h3>

              <p style="font-weight: bold;color:white;">{{ __('main.expired_license') }}</p>
            </div>
            <div class="icon">
              <i class="fa fa-user-secret"></i>
            </div>
            <a href="{{ route('drivers.expired') }}" class="small-box-footer">
              {{ __('main.visit') }} <i class="fa fa-arrow-circle-left"></i>
            </a>
          </div>
    </div>
    @endcan --}}
    @can('view_trip_cost')
    <div class="col-md-4 col-sm-12 col-xs-12 text-center">
		<div class="small-box text-center bg-danger">
            <div class="inner">
              <h3 style="color: transparent">.</h3>

              <p style="font-weight: bold;color:white;">{{ __('main.today transfer price') }}</p>
            </div>
            <div class="icon">
              <i class="fas fa-fw fa-money-bill-alt"></i>
            </div>
            @php
            $CostDate=App\CostDate::orderby('id','desc')->first();
            @endphp
            <a href="{{ route('locationCost.show',$CostDate->id) }}" class="small-box-footer">
              {{ __('main.visit') }} <i class="fa fa-arrow-circle-left"></i>
            </a>

          </div>
	</div>
  @endcan
  @can('view_service')
  <div class="col-md-4 col-sm-12 col-xs-12 text-center">
    <div class="small-box text-center bg-success">
       @php
            $services=App\Services::where('date',$today_date)->count();
            $ss =  App\Services::join('service_items','service_items.service_id','services.id')->where('services.date',$today_date)->select(DB::raw('(service_items.qty*service_items.price) as total'))->first();
            @endphp
            <div class="inner">
              <h4>{{ $services }} {{ __('main.dana') }} {{ __('main.with cost') }} @if($ss){{ $ss->total}}@else 0 @endif</h4>

              <p style="font-weight: bold;color:white;">{{ __('main.today services') }}</p>
            </div>
            <div class="icon">
              <i class="fas fa-fw fa-cog"></i>
            </div>

            <a href="{{ route('services.index') }}" class="small-box-footer">
              {{ __('main.visit') }} <i class="fa fa-arrow-circle-left"></i>
            </a>

          </div>
  </div>
  @endcan
  @can('view_buy_item')
  <div class="col-md-4 col-sm-12 col-xs-12 text-center">
    <div class="small-box text-center bg-info">
       @php
            $services=App\Items::select('alert_qty',DB::raw('(select sum(qty) from purchase_items where item_id=items.id) as purchase'),DB::raw('(select sum(qty) from service_items where item_id=items.id) as service'))->get();
            $items = 0;
            foreach($services as $s) {

              if(($s->purchase-$s->service)<$s->alert_qty) {
                $items+=1;
                // echo $s->purchase;
              }
            }
            @endphp

            <div class="inner">
              <h3 >{{ $items }}</h3>

              <p style="font-weight: bold;color:white;">{{ __('main.item alert qty') }}</p>
            </div>
            <div class="icon">
              <i class="fas fa-fw fa-cog"></i>
            </div>

            <a href="{{ route('items.index') }}" class="small-box-footer">
              {{ __('main.visit') }} <i class="fa fa-arrow-circle-left"></i>
            </a>

          </div>
  </div>
  @endcan
  
  <div class="col-md-4 col-sm-12 col-xs-12 text-center">
    <div class="small-box text-center bg-light" style="">
        <div class="inner">
            <h3 style="color: transparent">.</h3>

          <p style="font-weight: bold;">{{ __('main.monthly report') }}</p>
        </div>
        <div class="icon">
          <i class="fas fa-fw fa-file"></i>
        </div>
        <a href="{{ route('reports.monthly') }}" class="small-box-footer">
          {{ __('main.visit') }} <i class="fa fa-arrow-circle-left"></i>
        </a>
      </div>
</div>

  @can('view_driver')
<div class="col-md-4 col-sm-12 col-xs-12 text-center">
    <div class="small-box text-center " style="background-color: #3b76b3;">
        <div class="inner">
            <h3 >{{ App\Trucks::where('registeration_expire','<=',$today_date45)->count() }}</h3>

          <p style="font-weight: bold;">{{ __('main.expiring registeration') }}</p>
        </div>
        <div class="icon">
          <i class="fas fa-fw fa-calendar"></i>
        </div>
        <a href="{{ route('trucks.expired_registeration',1) }}" class="small-box-footer">
          {{ __('main.visit') }} <i class="fa fa-arrow-circle-left"></i>
        </a>
      </div>
</div>
@endcan
  @can('view_truck')
<div class="col-md-4 col-sm-12 col-xs-12 text-center">
    <div class="small-box text-center " style="background-color: #39CCCC;">
        <div class="inner">
            <h3 >{{ App\Trucks::where('permit_expire','<=',$today_date45)->count() }}</h3>

          <p style="font-weight: bold;">{{ __('main.expiring permit') }}</p>
        </div>
        <div class="icon">
          <i class="fas fa-fw fa-calendar"></i>
        </div>
        <a href="{{ route('trucks.expired_permit',1) }}" class="small-box-footer">
          {{ __('main.visit') }} <i class="fa fa-arrow-circle-left"></i>
        </a>
      </div>
</div>
@endcan
  @can('view_gas_driver')
<div class="col-md-4 col-sm-12 col-xs-12 text-center">
    <div class="small-box text-center bg-warning  " style="">
        @php
    $purchaseAmount=App\gassQtyPurchase::get()->sum("qty");
    $sellAmount=App\gassQtyToTrucks::get()->sum("qty");
    $totalAmount=$purchaseAmount - $sellAmount;
@endphp

        <div class="inner">
            <h3 >{{ $totalAmount }}</h3>

          <p style="font-weight: bold;">{{ __('main.gass available') }}</p>
        </div>
        <div class="icon">
          <i class="fas fa-fw fa-fire"></i>
        </div>
        <a href="{{ route('gass_purchase.index') }}" class="small-box-footer">
          {{ __('main.visit') }} <i class="fa fa-arrow-circle-left"></i>
        </a>
      </div>
</div>
@endcan
@can('view_banzin_driver')
<div class="col-md-4 col-sm-12 col-xs-12 text-center">
    <div class="small-box text-center bg-warning  " style="">
        @php
    $purchaseAmount=App\banzinQtyPurchase::get()->sum("qty");
    $sellAmount=App\banzinQtyToTrucks::get()->sum("qty");
    $totalAmount=$purchaseAmount - $sellAmount;
@endphp

        <div class="inner">
            <h3 >{{ $totalAmount }}</h3>

          <p style="font-weight: bold;">{{ __('main.banzin available') }}</p>
        </div>
        <div class="icon">
          <i class="fas fa-fw fa-fire"></i>
        </div>
        <a href="{{ route('banzin_purchase.index') }}" class="small-box-footer">
          {{ __('main.visit') }} <i class="fa fa-arrow-circle-left"></i>
        </a>
      </div>
</div>
@endcan
  @can('view_check')
<div class="col-md-4 col-sm-12 col-xs-12 text-center">
    <div class="small-box text-center  bg-gray-active color-palette" >
        <div class="inner">
            <h4 >{{ App\Checks::where('date','=',$today_date)->count() }} {{ __('main.truck') }} {{ App\CheckItems::join('checks','checks.id','check_items.check_id')->where('checks.date','=',$today_date)->count() }} {{ __('main.check') }} </h4>

          <p style="font-weight: bold;">{{ __('main.today checks') }}</p>
        </div>
        <div class="icon">
          <i class="fas fa-fw fa-heartbeat"></i>
        </div>
        <a href="{{ route('checks.index') }}" class="small-box-footer">
          {{ __('main.visit') }} <i class="fa fa-arrow-circle-left"></i>
        </a>
      </div>
</div>
@endcan
  @can('view_snduq')
<div class="col-md-4 col-sm-12 col-xs-12 text-center">
    <div class="small-box text-center  bg-purple color-palette" >
        <div class="inner">
            <h4 >{{ number_format( App\Slfa::sum('amount')-(App\DrivePayment::sum('amount')+App\Expenses::sum('cost'))) }}<br>
            ${{ number_format( App\Slfa::sum('dollar')-(App\DrivePayment::sum('dollar')+App\Expenses::sum('dollar'))) }}</h4>

          <p style="font-weight: bold;">{{ __('main.snduqs') }}</p>
        </div>
        <div class="icon">
          <i class="fas fa-university"></i>
        </div>
        <a href="{{ route('snduq.index') }}" class="small-box-footer">
          {{ __('main.visit') }} <i class="fa fa-arrow-circle-left"></i>
        </a>
      </div>
</div>
@endcan

</div>
@can('view_charts')
<div class="row">
  <div class="col col-md-6">{!! $chart2->container() !!}</div>

  <div class="col col-md-6" style="width:100%; height:12cm;"> {!! $chart->container() !!}</div>
</div>
@endcan
{{-- </div> --}}
   {!! $chart->script() !!}
   {!! $chart2->script() !!}
@stop