routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes(['register' => false]);
// Route::get('/', 'HomeController@index')->name('home');
Route::get('/', function () {
    if(Auth::check()){
        // if(Auth::user()->isPending() || Auth::user()->isDisabled()) {
            Auth::logout();
            return redirect('/login')->with('success', 'Please Login');
        // }
        //return view('welcome');
    }
    return redirect('/home');
});
Route::group(['middleware' => ['auth']], function() {
Route::resource('users', 'UserController');
Route::resource('roles', 'RoleController');

Route::resource('permissions', 'PermissionController');
Route::resource('drivers', 'DriverController');
Route::resource('trucks', 'TrucksController');
Route::resource('drives', 'DriveController');
Route::resource('items', 'ItemsController');
Route::resource('suppliers', 'SuppliersController');
Route::resource('warehouses', 'WarehouseController');
Route::resource('purchases', 'PurchaseController');
Route::resource('services', 'ServicesController');
Route::resource('checks', 'ChecksController');
Route::resource('snduq', 'SnduqController');
Route::resource('expenses', 'ExpensesController');
Route::resource('slfa', 'SlfaController');
Route::resource('purchase_items', 'PurchaseItemController');
Route::resource('service_items', 'ServiceItemsController');
Route::resource('check_items', 'CheckItemsController');
Route::resource('accounting','AccountingController');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/expired_license', 'DriverController@expired')->name('drivers.expired');
Route::get('/serviceouts/{id}', 'ServiceOutController@services')->name('serviceOut.services');
Route::post('/update/purchase_item', 'PurchaseItemController@updatee')->name('purchase_items.updatee');
Route::post('/trip/getPrice', 'TripController@getPrice')->name('trip.getprice');
Route::post('/trip/accounting', 'AccountingController@showaccounting')->name('accountant.showaccounting');
Route::post('/trip/finishaccounting', 'AccountingController@finishaccounting')->name('accountant.finishaccounting');
Route::post('/update/service_item', 'ServiceItemsController@updatee')->name('service_items.updatee');
Route::post('/update/service_out_item', 'ServiceOutItemsController@updatee')->name('service_out_items.updatee');
Route::post('/update/check_item', 'CheckItemsController@updatee')->name('check_items.updatee');
Route::get('/trucks/expired_reg/{id}', 'TrucksController@expired_registeration')->name('trucks.expired_registeration');
Route::get('/trucks/expired_permit/{id}', 'TrucksController@expired_permit')->name('trucks.expired_permit');
Route::get('/purchases/items/{id}', 'PurchaseController@items')->name('purchases.items');
Route::get('/services/items/{id}', 'ServicesController@items')->name('services.items');
Route::get('/serviceout/items/{id}', 'ServiceOutController@items')->name('serviceOut.items');
Route::get('/cheecks/items/{id}', 'ChecksController@items')->name('checks.items');
Route::get('/items/alert/{id}', 'ItemsController@alertItems')->name('items.alert');
Route::get('/items/projectparts/{id}', 'ItemsController@projectItems')->name('items.projectparts');
Route::resource('locations','LocationsController');
Route::resource('serviceOut','ServiceOutController');
Route::resource('service_out_items','ServiceOutItemsController');
Route::resource('projects','ProjectsController');
Route::resource('projectPayment','ProjectPaymentController');
Route::get('/projectPayments/{id}', 'ProjectPaymentController@payments')->name('projectpayments.payments');
Route::resource('fines','FinesController');
Route::resource('locationCost','LocationCostController');
Route::resource('materials','MaterialController');
Route::resource('expense_type','ExpenseTypeController');
Route::resource('trips','TripController');
Route::resource('transfers','BankTransferController');
Route::resource('dollars','DollarPriceController');
Route::resource('itemModel','ItemModelController');
Route::resource('itemSize','ItemSizeController');
Route::resource('drive_payments','DrivePaymentController');
Route::resource('gass_to_trucks','GassQtyToTrucksController');
Route::resource('gass_purchase','GassQtyPurchaseController');
Route::resource('banzin_to_trucks','BanzinQtyToTrucksController');
Route::resource('banzin_purchase','BanzinQtyPurchaseController');
Route::post('monthlyReport','ReportsController@monthly')->name('reports.monthly');
Route::post('transfer/updatestatus','BankTransferController@updatee')->name('transfers.updatee');
Route::get('monthlyReport','ReportsController@monthly')->name('reports.monthly');

Route::get('clear_cache', function () {

    \Artisan::call('migrate');
    \Artisan::call('cache:clear');

    dd("Cache is cleared");

});
});

resources/views/warehouses/create.blade.php
@extends('adminlte::page')
@section('head_scripts')
    <!-- DataTables CSS -->
    {{-- {{ HTML::style('css/plugins/dataTables.bootstrap.css') }} --}}
@stop
@section('content')
<style type="text/css">
	td{
		text-align: center;
	}
	th {
		text-align: center !important;
	}
</style>

<div class="card card-primary">
            <div class="card-header with-border text-center">
              {{ __('main.new warehouse') }}
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form role="form" action="{{ route('warehouses.store') }}" method="POST">
            	    {{csrf_field()}}
          <input type="hidden" name="_token" value="<?php echo csrf_token(); ?>">
              <div class="card-body">
                <div class="form-group">
                  <label >{{ __('main.name') }}</label>
                  <input type="text" class="form-control"  placeholder="{{ __('main.name') }}" name="name" required>
                </div>

                 <div class="form-group">
                  <label >{{ __('main.description') }}</label>
                  <input type="text" class="form-control"  placeholder="{{ __('main.description') }}" name="description">

                </div>
               
              </div>
              <!-- /.box-body -->

              <div class="card-footer">
                <button type="submit" class="btn btn-success"><i class="fa fa-fw fa-save"></i>{{ __('main.save') }}</button>
              </div>
            </form>
          </div>
@stop

resources/views/warehouses/edit.blade.php
@extends('adminlte::page')
@section('head_scripts')
    <!-- DataTables CSS -->
    {{-- {{ HTML::style('css/plugins/dataTables.bootstrap.css') }} --}}
@stop
@section('content')
<style type="text/css">
	td{
		text-align: center;
	}
	th {
		text-align: center !important;
	}
</style>

<div class="card card-primary">
            <div class="card-header with-border text-center">
              {{ __('main.update warehouse') }}
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form role="form" action="{{ route('warehouses.update',$warehouse->id) }}" method="POST">
            	     {{csrf_field()}}
                     <input type="hidden" name="_token" value="<?php echo csrf_token(); ?>">
          <input type="hidden" name="_method" value="PUT">
              <div class="card-body">
                <div class="form-group">
                  <label >{{ __('main.name') }}</label>
                  <input type="text" class="form-control"  placeholder="{{ __('main.name') }}" name="name" value="{{ $warehouse->name }}" required>
                </div>
              
                
                
                 <div class="form-group">
                  <label >{{ __('main.description') }}</label>
                  <input type="text" class="form-control"  placeholder="{{ __('main.description') }}" name="description" value="{{ $warehouse->description }}">

                </div>
               
              </div>
              <!-- /.box-body -->

              <div class="card-footer">
                <button type="submit" class="btn btn-success"><i class="fa fa-fw fa-save"></i>{{ __('main.save') }}</button>
              </div>
            </form>
          </div>
@stop

resources/views/warehouses/index.blade.php
@extends('adminlte::page')
@section('head_scripts')
    <!-- DataTables CSS -->
    {{-- {{ HTML::style('css/plugins/dataTables.bootstrap.css') }} --}}
@stop
@section('content')
<h3>{{ __('main.warehouses') }}</h3>
    <div class="card card-light">
        <div class="card-header bg-light">
             @can('add_warehouse')<a  href="{{ route('warehouses.create') }}"><button type="button" class="btn btn-dark"><i class="fa fa-fw fa-plus"></i>{{ __('main.new') }}</button></a>@endcan
        </div>
        <div class="card-body">
            <div class="table-responsive">
    <table   table id="example" class="table table-hover" >
        <thead class="thead-dark">
            <tr>
                <th>#</th>
                <th>{{ __('main.name') }}</th>

                <th>{{ __('main.stock') }}</th>
                <th>{{ __('main.stock cost') }}</th>
                <th>{{ __('main.description') }}</th>

               @can('edit_warehouse')<th>{{ __('main.edit') }}</th>@endcan
                @can('delete_warehouse')<th>{{ __('main.delete') }}</th>@endcan
            </tr>
        </thead>
        <tbody>
        	@foreach(App\Warehouse::all() as $d)
            <tr>
                <td>{{ $loop->iteration }}</td>
                <td>{{ $d->name }}</td>
                <td>0</td>
                <td>0</td>
                {{-- <td>{{ $d->code }}</td> --}}
                {{-- <td>{{ $d->location }}</td> --}}
                <td>{{ $d->description }}</td>
                {{-- <td>{{ $d->note }}</td> --}}
                @can('edit_warehouse')<td>
                   <form method="GET" action="{{ route('warehouses.edit',$d->id) }}">
                                    {{ csrf_field() }}
  <input type="hidden" name="_token" value="<?php echo csrf_token(); ?>">
                                    <div class="form-group">
                                        <input type="submit" class="btn btn-info btn-sm " value="{{ __('main.edit') }}" >

                                    </div>
                                </form></td>@endcan
                @can('delete_warehouse')<td>
                                <form action="{{ route('warehouses.destroy',$d->id) }}" method="post">
                         {{ csrf_field() }}
                           <input type="hidden" name="_token" value="<?php echo csrf_token(); ?>">
                                <input type="hidden" name="_method" value="DELETE"  >

                    <a style="padding: 0px;
                      font-size: 12px;
                      color: red;" role="menuitem" tabindex="-1"  onclick="return confirm('{{ __('main.are you sure') }}')">
                      <button type="submit" class="btn btn-sm btn-danger"><i class="fa fa-fw fa-trash"></i></button>
                    </a>
                  </form>
                  </td>@endcan
            </tr>
             @endforeach
        </tbody>
    </table>
            </div>

        </div>
    </div>
@stop