routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes(['register' => false]);
// Route::get('/', 'HomeController@index')->name('home');
Route::get('/', function () {
    if(Auth::check()){
        // if(Auth::user()->isPending() || Auth::user()->isDisabled()) {
            Auth::logout();
            return redirect('/login')->with('success', 'Please Login');
        // }
        //return view('welcome');
    }
    return redirect('/home');
});
Route::group(['middleware' => ['auth']], function() {
Route::resource('users', 'UserController');
Route::resource('roles', 'RoleController');

Route::resource('permissions', 'PermissionController');
Route::resource('drivers', 'DriverController');
Route::resource('trucks', 'TrucksController');
Route::resource('drives', 'DriveController');
Route::resource('items', 'ItemsController');
Route::resource('suppliers', 'SuppliersController');
Route::resource('warehouses', 'WarehouseController');
Route::resource('purchases', 'PurchaseController');
Route::resource('services', 'ServicesController');
Route::resource('checks', 'ChecksController');
Route::resource('snduq', 'SnduqController');
Route::resource('expenses', 'ExpensesController');
Route::resource('slfa', 'SlfaController');
Route::resource('purchase_items', 'PurchaseItemController');
Route::resource('service_items', 'ServiceItemsController');
Route::resource('check_items', 'CheckItemsController');
Route::resource('accounting','AccountingController');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/expired_license', 'DriverController@expired')->name('drivers.expired');
Route::get('/serviceouts/{id}', 'ServiceOutController@services')->name('serviceOut.services');
Route::post('/update/purchase_item', 'PurchaseItemController@updatee')->name('purchase_items.updatee');
Route::post('/trip/getPrice', 'TripController@getPrice')->name('trip.getprice');
Route::post('/trip/accounting', 'AccountingController@showaccounting')->name('accountant.showaccounting');
Route::post('/trip/finishaccounting', 'AccountingController@finishaccounting')->name('accountant.finishaccounting');
Route::post('/update/service_item', 'ServiceItemsController@updatee')->name('service_items.updatee');
Route::post('/update/service_out_item', 'ServiceOutItemsController@updatee')->name('service_out_items.updatee');
Route::post('/update/check_item', 'CheckItemsController@updatee')->name('check_items.updatee');
Route::get('/trucks/expired_reg/{id}', 'TrucksController@expired_registeration')->name('trucks.expired_registeration');
Route::get('/trucks/expired_permit/{id}', 'TrucksController@expired_permit')->name('trucks.expired_permit');
Route::get('/purchases/items/{id}', 'PurchaseController@items')->name('purchases.items');
Route::get('/services/items/{id}', 'ServicesController@items')->name('services.items');
Route::get('/serviceout/items/{id}', 'ServiceOutController@items')->name('serviceOut.items');
Route::get('/cheecks/items/{id}', 'ChecksController@items')->name('checks.items');
Route::get('/items/alert/{id}', 'ItemsController@alertItems')->name('items.alert');
Route::get('/items/projectparts/{id}', 'ItemsController@projectItems')->name('items.projectparts');
Route::resource('locations','LocationsController');
Route::resource('serviceOut','ServiceOutController');
Route::resource('service_out_items','ServiceOutItemsController');
Route::resource('projects','ProjectsController');
Route::resource('projectPayment','ProjectPaymentController');
Route::get('/projectPayments/{id}', 'ProjectPaymentController@payments')->name('projectpayments.payments');
Route::resource('fines','FinesController');
Route::resource('locationCost','LocationCostController');
Route::resource('materials','MaterialController');
Route::resource('expense_type','ExpenseTypeController');
Route::resource('trips','TripController');
Route::resource('transfers','BankTransferController');
Route::resource('dollars','DollarPriceController');
Route::resource('itemModel','ItemModelController');
Route::resource('itemSize','ItemSizeController');
Route::resource('drive_payments','DrivePaymentController');
Route::resource('gass_to_trucks','GassQtyToTrucksController');
Route::resource('gass_purchase','GassQtyPurchaseController');
Route::resource('banzin_to_trucks','BanzinQtyToTrucksController');
Route::resource('banzin_purchase','BanzinQtyPurchaseController');
Route::post('monthlyReport','ReportsController@monthly')->name('reports.monthly');
Route::post('transfer/updatestatus','BankTransferController@updatee')->name('transfers.updatee');
Route::get('monthlyReport','ReportsController@monthly')->name('reports.monthly');

Route::get('clear_cache', function () {

    \Artisan::call('migrate');
    \Artisan::call('cache:clear');

    dd("Cache is cleared");

});
});

app/ServiceOut.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ServiceOut extends Model
{
    //
    //  public function drive()
    // {
    //     return $this->belongsTo('App\Drive','drive_id');
    // }
    public function project()
    {
        return $this->belongsTo('App\Projects','id_project');
    }
}

app/Http/Controllers/ServiceOutController.php
<?php

namespace App\Http\Controllers;

use App\ServiceOut;
use App\ServiceOutItems;
use Illuminate\Http\Request;

class ServiceOutController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('service_out.index');
    }
     public function services($id)
    {
        //
        return view('service_out.index',compact('id'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $s = new ServiceOut();
        $s->id_project= $request->project_id;
        $s->date= $request->date;
        $s->plate= $request->plate;
        $s->fee= $request->fee;
        $s->invoice_no= $request->invoice_no;
        $s->note= $request->note;
        $s->save();

        return redirect(route('serviceOut.index'))->with('success', trans('main.Service Added Successfully'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\ServiceOut  $serviceOut
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\ServiceOut  $serviceOut
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $service = ServiceOut::find($id);
        return view('service_out.edit',compact('service'));
    }
public function items($id)
    {
        //
        $service = ServiceOut::find($id);
        return view('service_out.items',compact('service'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\ServiceOut  $serviceOut
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
         $s =  ServiceOut::find($id);
        $s->id_project= $request->project_id;
        $s->date= $request->date;
        $s->plate= $request->plate;
        $s->fee= $request->fee;
        $s->invoice_no= $request->invoice_no;
        $s->note= $request->note;
        $s->save();

        return redirect(route('serviceOut.index'))->with('success', trans('main.Service Updated Successfully'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\ServiceOut  $serviceOut
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $service = ServiceOut::find($id);
        ServiceOutItems::where('id_service',$id)->delete();
        $service->destroy($id);
        return redirect(route('serviceOut.index'))->with('success', trans('main.Service Deleted Successfully'));
    }
}

resources/views/service_out/edit.blade.php
@extends('adminlte::page')
@section('head_scripts')
    <!-- DataTables CSS -->
    {{-- {{ HTML::style('css/plugins/dataTables.bootstrap.css') }} --}}
@stop
@section('content')
 <div class="modal-content">
      <div class="modal-header">
        {{-- <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button> --}}
        <h4 class="modal-title" align="center"><b> {{ __("main.update") }}  {{ __("main.service") }}</b></h4>
      </div>
      <div class="modal-body" style="overflow-y: scroll;">
        <form action="{{ route('serviceOut.update',$service->id) }}" method="POST" enctype="multipart/form-data">
                {{csrf_field()}}
                  <input type="hidden" name="_token" value="<?php echo csrf_token(); ?>">
<input type="hidden" name="_method" value="PUT">
          <div class="form-group">
                <label>{{ __("main.project") }}</label>
                <input type="hidden" name="project_id" id="project_id" value="{{ $service->id_project }}">
                <input list="projectslist" name="projects" id="projects" class="form-control" onchange="selectproject(this.value)" required value="{{ $service->project->id }}">
                <datalist id="projectslist">
                  @foreach(App\Projects::all() as $c)
                  <option value="{{ $c->id }}-{{ $c->name }}">{{ $c->name }} </option>
                  @endforeach
                </datalist>

              </div>
 

          <div class="form-group">
            <input type="text" name="project" id="project" readonly value="{{ $service->project->name }}">
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1"> {{ __("main.plate") }}</label>
              <input type="text" id="plate" name="plate" class="form-control" placeholder="plate" required value="{{ $service->plate }}">
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1"> {{ __("main.date") }}</label>
              <input type="date" id="date" name="date" class="form-control" placeholder="Date" required value="{{ $service->date }}">
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1"> {{ __("main.invoice_no") }}</label>
              <input type="text" id="invoice_no" name="invoice_no" class="form-control" placeholder="{{ __('main.invoice_no') }}" value="{{ $service->invoice_no }}">
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1"> {{ __("main.fee") }}</label>
              <input type="text" id="fee" name="fee" class="form-control" placeholder="{{ __('main.fee') }}" value="{{ $service->fee }}">
          </div>
         {{--  <div class="form-group">
            <label for="exampleInputEmail1"> {{ __("main.current mileage") }}</label>
              <input type="text" id="mileage" name="mileage" class="form-control" placeholder="{{ __('main.mileage') }}" >
          </div> --}}
        
         {{--  <div class="form-group">
            <label for="exampleInputEmail1"> {{ __("main.discount") }}</label>
              <input type="number" id="discount" name="discount" class="form-control" placeholder="{{ __('main.discount') }}" required value='0'>
          </div> --}}
          <div class="form-group">
            <label for="exampleInputEmail1"> {{ __("main.note") }}</label>
              <input type="text" id="note" name="note" class="form-control" placeholder="{{ __('main.note') }}"  >
          </div>


          <button type="submit" class="btn btn-primary"> {{ __("main.add") }}</button>
        </form>
      </div>
        {{-- <div class="modal-footer">
            <button type="button" class="btn btn-default pull-left" data-dismiss="modal"> {{ __("main.cancel") }}</button>

          </div> --}}
    </div>
    @stop

resources/views/service_out/index.blade.php
@extends('adminlte::page')
@section('head_scripts')
    <!-- DataTables CSS -->
    {{-- {{ HTML::style('css/plugins/dataTables.bootstrap.css') }} --}}
@stop 
@section('content')
<h3>{{ __('main.services out') }}</h3>
    <div class="card card-light">
        <div class="card-header bg-info">
          @can('add_project_service')  <a class="btn btn-light noprint" data-toggle="modal" data-target="#new-service-modal" style="font-size: 18px;float:right; color:black !important;">
                <i class="fa fa-plus"></i> {{ __("main.new") }}
              </a>@endcan
        </div>
        <div class="card-body">
            <div class="table-responsive">
    <table id="example" class="table table-hover ">
        <thead class="">
            <tr>
                <th>#</th>
                <th>{{ __('main.project') }}</th>
                <th>{{ __('main.plate') }}</th>
                <th>{{ __('main.date') }}</th>
                <th>{{ __('main.invoice_no') }}</th>
                {{-- <th>{{ __('main.discount') }}</th> --}}
                <th>{{ __('main.total') }}</th>
                <th>{{ __('main.total cost') }}</th>
                {{-- <th>{{ __('main.total cost $') }}</th> --}}
                {{-- <th>{{ __('main.invoice_no') }}</th> --}}
                <th>{{ __('main.note') }}</th>
                <th>{{ __('main.items') }}</th>
                @can('edit_project_service') <th>{{ __('main.edit') }}</th>@endcan
                 @can('delete_project_service')<th>{{ __('main.delete') }}</th>@endcan
            </tr>
        </thead>
        <tbody>
          @php
          // echo $id;
          if(isset($id)) $services = App\ServiceOut::where('id_project',$id)->orderby('id','desc')->get(); 
          else $services = App\ServiceOut::orderby('id','desc')->get(); 
          @endphp
        	@foreach($services as $d)
            <tr>
                <td>{{ $loop->iteration }}</td>
                <td>{{ $d->project->name }}</td>
                <td>{{ $d->plate }}</td>
                <td>{{ $d->date }}</td>
                <td>{{ $d->invoice_no }}</td>
                <td>{{ number_format( App\ServiceOutItems::where('id_service',$d->id)->select(DB::raw('sum(qty) as total'))->first()->total,2) }} </td>
                <td>{{ number_format( App\ServiceOutItems::where('id_service',$d->id)->select(DB::raw('sum(qty*price) as total'))->first()->total+$d->fee,2) }} </td>
                {{-- <td>{{ number_format( App\ServiceOutItems::where('id_service',$d->id)->select(DB::raw('sum(qty*dollar) as total'))->first()->total,2) }} </td> --}}
                <td>{{ $d->note }}</td>
                 @can('view_project_service')<td>
                   <form method="GET" action="{{ route('serviceOut.items',$d->id) }}">
                                    {{ csrf_field() }}
  <input type="hidden" name="_token" value="<?php echo csrf_token(); ?>">
                                    <div class="form-group">
                                        <input type="submit" class="btn btn-warning btn-sm " value="{{ __('main.items') }}" >

                                    </div>
                                </form></td>@endcan
                 @can('edit_project_service')<td>
                   <form method="GET" action="{{ route('serviceOut.edit',$d->id) }}">
                                    {{ csrf_field() }}
  <input type="hidden" name="_token" value="<?php echo csrf_token(); ?>">

                                    <div class="form-group">
                                        <input type="submit" class="btn btn-info btn-sm " value="{{ __('main.edit') }}" >

                                    </div>
                                </form></td>@endcan
                 @can('delete_project_service')<td>
                                <form action="{{ route('serviceOut.destroy',$d->id) }}" method="post">
                         {{ csrf_field() }}
                           <input type="hidden" name="_token" value="<?php echo csrf_token(); ?>">
                                <input type="hidden" name="_method" value="DELETE"  >

                    <a style="padding: 0px;
                      font-size: 12px;
                      color: red;" role="menuitem" tabindex="-1"  onclick="return confirm('{{ __('main.are you sure') }}')">
                      <button type="submit" class="btn btn-sm btn-danger"><i class="fa fa-fw fa-trash"></i></button>
                    </a>
                  </form>
                  </td>@endcan
            </tr>
             @endforeach
        </tbody>

    </table>
</div>
<div class="modal fade" id="new-service-modal" >
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" align="center"><b> {{ __("main.new") }}  {{ __("main.service") }}</b></h4>
      </div>
      <div class="modal-body" style="overflow-y: scroll;">
        <form action="{{ route('serviceOut.store') }}" method="POST" enctype="multipart/form-data">
                {{csrf_field()}}
          <input type="hidden" name="_token" value="<?php echo csrf_token(); ?>">
          <div class="form-group">
                <label>{{ __("main.project") }}</label>
                <input type="hidden" name="project_id" id="project_id">
                <input list="projectslist" name="projects" id="projects" class="form-control" onchange="selectproject(this.value)" required>
                <datalist id="projectslist">
                  @foreach(App\Projects::all() as $c)
                  <option value="{{ $c->id }}-{{ $c->name }}">{{ $c->name }} </option>
                  @endforeach
                </datalist>

              </div>
 

          <div class="form-group">
            <input type="text" name="project" id="project" readonly>
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1"> {{ __("main.plate") }}</label>
              <input type="text" id="plate" name="plate" class="form-control" placeholder="plate" required >
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1"> {{ __("main.date") }}</label>
              <input type="date" id="date" name="date" class="form-control" placeholder="Date" required value="{{date('Y-m-d', strtotime('+0 day'))}}">
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1"> {{ __("main.invoice_no") }}</label>
              <input type="text" id="invoice_no" name="invoice_no" class="form-control" placeholder="{{ __('main.invoice_no') }}" >
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1"> {{ __("main.fee") }}</label>
              <input type="text" id="fee" name="fee" class="form-control" placeholder="{{ __('main.fee') }}" value="0">
          </div>
         {{--  <div class="form-group">
            <label for="exampleInputEmail1"> {{ __("main.current mileage") }}</label>
              <input type="text" id="mileage" name="mileage" class="form-control" placeholder="{{ __('main.mileage') }}" >
          </div> --}}
        
         {{--  <div class="form-group">
            <label for="exampleInputEmail1"> {{ __("main.discount") }}</label>
              <input type="number" id="discount" name="discount" class="form-control" placeholder="{{ __('main.discount') }}" required value='0'>
          </div> --}}
          <div class="form-group">
            <label for="exampleInputEmail1"> {{ __("main.note") }}</label>
              <input type="text" id="note" name="note" class="form-control" placeholder="{{ __('main.note') }}"  >
          </div>


          <button type="submit" class="btn btn-primary"> {{ __("main.add") }}</button>
        </form>
      </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default pull-left" data-dismiss="modal"> {{ __("main.cancel") }}</button>

          </div>
    </div>
  </div>
</div>
        </div>
    </div>
    <script type="text/javascript">
      function selectproject(id) {
        // body...
        $('#project_id').val(id.split("-")[0]);
    $('#project').val(id.split("-")[1]);
      }
    </script>
@stop

resources/views/service_out/items.blade.php
@extends('adminlte::page')
@section('head_scripts')
    <!-- DataTables CSS -->
    {{-- {{ HTML::style('css/plugins/dataTables.bootstrap.css') }} --}}
@stop
@section('content')
<style type="text/css">
  .dataTables_info{
    display: none;
  }
</style>
<h3>{{ __('main.items') }}</h3>
{{-- <a  href="{{ route('items.create') }}"><button type="button" class="btn btn-success"><i class="fa fa-fw fa-plus"></i>{{ __('main.new') }}</button></a> --}}
<div class="card card-success">
    <div class="card-body">
        <div class="row">
            <div class="col-md-2">{{ __('main.project') }}</div>
            <div class="col-md-4"><h3>{{ $service->project->name }}</h3></div>
            <div class="col-md-2">{{ __('main.plate') }}</div>
            <div class="col-md-4"><h3>{{ $service->plate }}</h3></div>
        </div>

        <hr>
        <div class="row">
            <div class="col-md-2">{{ __('main.invoice_no') }}</div>
            <div class="col-md-4">{{ $service->invoice_no }}</div>
            <div class="col-md-2">{{ __('main.date') }}</div>
            <div class="col-md-4">{{ $service->date }}</div>
        </div>
        <hr>
        <div class="row">
            <div class="col-md-2">{{ __('main.note') }}</div>
            <div class="col-md-4">{{ $service->note }}</div>
            <div class="col-md-2">{{ __('main.fee') }}</div>
            <div class="col-md-4">{{ number_format($service->fee,2) }}</div>
        </div>
        <div class="row">

        </div>
    </div>
</div>
<div class="card card-success responsive">
    <div class="card-body">
<table  class="display stripe table table-bordered table-hover" style="width:100%">
        <thead>
            <tr>
                <th>#</th>
                <th>{{ __('main.item') }}</th>
                <th>{{ __('main.code') }}</th>
                <th>{{ __('main.qty') }}</th>
                <th>{{ __('main.price') }}</th>
                <th>{{ __('main.note') }}</th>
                {{-- <th>{{ __('main.edit') }}</th> --}}
                <th>{{ __('main.delete') }}</th>
            </tr>
        </thead>
        <tbody>
        	@foreach(App\ServiceOutItems::where('id_service',$service->id)->get() as $d)
            <tr>
                <td>{{ $loop->iteration }}</td>
                <td>{{ $d->item->name }}</td>
                <td>{{ $d->item->code }}</td>
                <td><input type="number" step="0.01" value="{{ $d->qty }}" style="width:100%; margin:0px;text-align: center;" onblur="updateitem('qty',{{ $d->id }},this.value)"></td>
                <td><input type="number" step="0.01" value="{{ $d->price }}" style="width:100%; margin:0px;text-align: center;" onblur="updateitem('price',{{ $d->id }},this.value)"  ></td>
                <td><input type="text"  value="{{ $d->note }}" style="width:100%; margin:0px;text-align: center;"onblur="updateitem('note',{{ $d->id }},this.value)" ></td>

                <td>
                                <form action="{{ route('service_out_items.destroy',$d->id) }}" method="post">
                         {{ csrf_field() }}
                           <input type="hidden" name="_token" value="<?php echo csrf_token(); ?>">
                                <input type="hidden" name="_method" value="DELETE"  >

                    <a style="padding: 0px;
                      font-size: 12px;
                      color: red;" role="menuitem" tabindex="-1"  onclick="return confirm('{{ __('main.are you sure') }}')">
                      <button type="submit" class="btn btn-sm btn-danger"><i class="fa fa-fw fa-trash"></i></button>
                    </a>
                  </form>
                  </td>
            </tr>
             @endforeach

        </tbody>
        <tfoot>
            <tr><td colspan="3">{{ __('main.total_item') }}</td>
                <td><input style="width:100%;text-align: center;" type="number"   id="total_qty" value="{{ App\ServiceOutItems::where('id_service',$service->id)->sum('qty') }}"   disabled="true" ></td>

                <td colspan="2"></td>
                </tr>
        </tfoot>
    </table>
    {{-- <hr>

    <div class="row text-center">
        <div class="col-md-2"><h4>{{ __('main.new') }}</h4></div>
        <div class="col-md-2"> <input list="itemslist" name="item_id" id="item_id" class="form-control" onchange="hideList(this)" placeholder="{{ __('main.item') }}">
                <datalist id="itemslist">
                  @foreach(App\Items::all() as $c)
                  <option value="{{ $c->id }}">{{ $c->name }}-{{ $c->code }} </option>
                  @endforeach
                </datalist></div>
                <div class="col-md-2"><input type="number" step="0.01" name="qty" placeholder="{{ __('main.qty') }}" id="qty"></div>
                <div class="col-md-2"><input type="number" step="0.01" name="price" placeholder="{{ __('main.price') }}" id="price"></div>
                <div class="col-md-2"><input type="text"  name="invoice_no" placeholder="{{ __('main.invoice_no') }}" id="invoice_no"></div>
                <div class="col-md-2"><input type="text"  name="note" placeholder="{{ __('main.note') }}" id="note"></div>
                <div class="col-md-2"><button onclick="additem({{ $service->id }})" type="submit" class="btn btn-success"><i class="fa fa-fw fa-save" ></i>{{ __('main.add') }}</button></div>
    </div> --}}
{{-- </form> --}}
     </div>
 </div>


<div class="card card-light">
    <div class="card-body">
        <div class="table-responsive">
        <table id="example1" class="table table-hover" >
                <thead class="thead-dark">
                    <tr>
                        <th>#</th>
                        <th>{{ __('main.add') }}</th>
                        <th>{{ __('main.name') }}</th>
                        <th>{{ __('main.code') }}</th>
                        <th>{{ __('main.location') }}</th>
                        <th>{{ __('main.description') }}</th>
                        <th>{{ __('main.note') }}</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach(App\Items::where('model_id',2)->get() as $d)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td><button type="button" class="btn btn-block btn-success" onclick="addItem({{ $service->id }},{{ $d->id }})"> <i class="fa fa-plus"></i> {{ __("main.add") }}</button></td>
                        <td>{{ $d->name }}</td>
                        <td>{{ $d->code }}</td>
                        <td>{{ $d->location }}</td>
                        <td>{{ $d->description }}</td>
                        <td>{{ $d->note }}</td>
                    </tr>
                     @endforeach
                </tbody>
            </table>
        </div>
        </div>
</div>



<script type="text/javascript">
    function additem(service_id)
{
  //
  console.log(service_id);
  var item_id = document.getElementById('item_id').value;
  // var qty = document.getElementById('qty').value;
  // var invoice_no = document.getElementById('invoice_no').value;
  // var price = document.getElementById('price').value;
  // var note = document.getElementById('note').value;
  // console.log(item_id);
  // console.log(qty);
  // console.log(customer_id);
  $.ajax({
          type:'POST',
          headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
          url:'{{ route("service_out_items.store") }}',
          data:{ service_id:service_id, item_id:item_id},
           success:function(data){
            console.log(data);
            location.reload();
           }
        });
}
function addItem(service_id,item_id)
{
  console.log(service_id);
  // var item_id = document.getElementById('item_id').value;
  var qty = 0;//document.getElementById('qty').value;
  // var invoice_no = document.getElementById('invoice_no').value;
  var price =0;// document.getElementById('price').value;
  var note = '';//document.getElementById('note').value;
  // console.log(item_id);
  // console.log(qty);
  // console.log(customer_id);
  $.ajax({
          type:'POST',
          headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
          url:'{{ route("service_out_items.store") }}',
          data:{ service_id:service_id, item_id:item_id, qty:qty,price:price, note:note},
           success:function(data){
            console.log(data);
            location.reload();
           }
        });
}
function updateitem(field,id,val)
{
  console.log(field);
  console.log(id);
  console.log(val);

  $.ajax({
          type:'POST',
          headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
          url:'{{ route("service_out_items.updatee") }}',
          data:{ id:id, field:field,val:val},
           success:function(data){
            console.log(data);
            // console.log(data['total_qty']);
            // console.log(data['total']);
            // document.getElementById("total_qty").value =data['total_qty'];
            // document.getElementById("total").value =data['total'];
           }
        });
}
</script>

@stop